export type CatalogProduct = {
  sku: string;
  name: string;
  sub: string;
  description: string;
  category: 'Footwear' | 'Apparel';
  priceKes: number;
  image: string;
  sizes?: string[];
  colors?: { name: string; swatch: string }[];
};

const colors = {
  black: { name: 'Black', swatch: '#111111' },
  brown: { name: 'Brown', swatch: '#573D32' },
  white: { name: 'White', swatch: '#FFFFFF' },
  red: { name: 'Red', swatch: '#C52835' },
  pink: { name: 'Pink', swatch: '#E681A5' },
  navy: { name: 'Navy', swatch: '#263957' },
  grey: { name: 'Grey', swatch: '#858A91' },
  blue: { name: 'Blue', swatch: '#315BB5' },
};

export const catalogProducts: CatalogProduct[] = [
  {
    sku: 'M16-BOOT-PATENT',
    name: 'Patent Over-the-Knee Boots',
    sub: 'Glossy tall boots',
    description: 'A glossy, over-the-knee silhouette with a pointed toe and slim heel.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/patent-over-the-knee-boots.jpg',
    colors: [colors.black, colors.brown, colors.white, colors.red],
  },
  {
    sku: 'M16-STRAP-SNEAKER',
    name: 'Chunky Strap Sneakers',
    sub: 'Statement platform sneakers',
    description: 'Chunky sole sneakers with bold contrast straps.',
    category: 'Footwear',
    priceKes: 5000,
    image: '/products/m16drip/chunky-strap-sneakers.jpg',
    colors: [colors.black, colors.red, colors.white],
  },
  {
    sku: 'M16-RETRO-RUNNER',
    name: 'Retro Colour-Block Runner',
    sub: 'Colour-block running style',
    description: 'A retro-inspired runner with layered panels and a cushioned-looking sole.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/retro-colour-block-runner.jpg',
    colors: [colors.white, colors.red, colors.grey],
  },
  {
    sku: 'M16-VIOLET-CHUNKY',
    name: 'Violet Chunky Trainers',
    sub: 'Chunky everyday trainers',
    description: 'Chunky trainers in a violet and lilac colourway.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/violet-chunky-trainers.jpg',
  },
  {
    sku: 'M16-WHITE-CHUNKY',
    name: 'White Chunky Trainers',
    sub: 'Chunky everyday trainers',
    description: 'White trainers with a sculpted, chunky sole.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/white-chunky-trainers.jpg',
  },
  {
    sku: 'M16-RED-GREY-RUNNER',
    name: 'Red and Grey Running Shoes',
    sub: 'Colour-block sports shoes',
    description: 'Light-coloured sports shoes with red and grey accents.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/red-grey-running-shoes.jpg',
  },
  {
    sku: 'M16-NAVY-LOWTOP',
    name: 'Navy Low-Top Sneakers',
    sub: 'Casual low-top shoes',
    description: 'A clean, low-top sneaker in deep navy.',
    category: 'Footwear',
    priceKes: 3500,
    image: '/products/m16drip/navy-low-top-sneakers.jpg',
  },
  {
    sku: 'M16-BLACK-SLIPON',
    name: 'Black Casual Slip-Ons',
    sub: 'Everyday slip-on shoes',
    description: 'A simple black slip-on with a low profile.',
    category: 'Footwear',
    priceKes: 3500,
    image: '/products/m16drip/black-casual-slip-ons.jpg',
  },
  {
    sku: 'M16-BLACK-TAN-SLIPON',
    name: 'Black and Tan Slip-Ons',
    sub: 'Two-tone casual shoes',
    description: 'Black slip-ons with a contrasting tan sole.',
    category: 'Footwear',
    priceKes: 3500,
    image: '/products/m16drip/black-tan-slip-ons.jpg',
  },
  {
    sku: 'M16-RED-CANVAS',
    name: 'Red Canvas Sneakers',
    sub: 'Canvas low-top shoes',
    description: 'A bright red canvas sneaker with a white sole.',
    category: 'Footwear',
    priceKes: 3000,
    image: '/products/m16drip/red-canvas-sneakers.jpg',
  },
  {
    sku: 'M16-PURPLE-CANVAS',
    name: 'Purple Canvas Sneakers',
    sub: 'Canvas low-top shoes',
    description: 'A purple canvas low-top with a contrasting sole.',
    category: 'Footwear',
    priceKes: 3000,
    image: '/products/m16drip/purple-canvas-sneakers.jpg',
  },
  {
    sku: 'M16-BLUE-CANVAS',
    name: 'Blue Canvas Sneakers',
    sub: 'Canvas low-top shoes',
    description: 'A blue canvas low-top with matching laces.',
    category: 'Footwear',
    priceKes: 3000,
    image: '/products/m16drip/blue-canvas-sneakers.jpg',
  },
  {
    sku: 'M16-STRAPPY-BLACK-HEEL',
    name: 'Black Strappy Heels',
    sub: 'Ankle-strap heels',
    description: 'Slim black heels with wraparound ankle straps.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/black-strappy-heels.jpg',
  },
  {
    sku: 'M16-SILVER-STRAP-HEEL',
    name: 'Silver Strap Heels',
    sub: 'Metallic ankle-strap heels',
    description: 'Metallic silver heels with delicate ankle straps.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/silver-strap-heels.jpg',
  },
  {
    sku: 'M16-WHITE-STRAP-HEEL',
    name: 'White Strap Heels',
    sub: 'Ankle-strap heels',
    description: 'White pointed heels with ankle straps.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/white-strap-heels.jpg',
  },
  {
    sku: 'M16-PINK-STRAP-HEEL',
    name: 'Pink Strap Heels',
    sub: 'Ankle-strap heels',
    description: 'Pink open-toe heels with slim ankle straps.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/pink-strap-heels.jpg',
  },
  {
    sku: 'M16-BLUE-ANKLE-BOOT',
    name: 'Blue Ankle Boots',
    sub: 'Lace-up ankle boots',
    description: 'A bright blue lace-up boot with a sturdy sole.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/blue-ankle-boots.jpg',
  },
  {
    sku: 'M16-WHITE-ANKLE-BOOT',
    name: 'White Ankle Boots',
    sub: 'Lace-up ankle boots',
    description: 'A white lace-up boot with a sturdy sole.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/white-ankle-boots.jpg',
  },
  {
    sku: 'M16-RED-ANKLE-BOOT',
    name: 'Red Ankle Boots',
    sub: 'Lace-up ankle boots',
    description: 'A red lace-up boot with a sturdy sole.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/red-ankle-boots.jpg',
  },
  {
    sku: 'M16-RETRO-CANVAS',
    name: 'Retro Canvas Low-Tops',
    sub: 'Classic canvas sneakers',
    description: 'A classic canvas low-top with contrast trim.',
    category: 'Footwear',
    priceKes: 3000,
    image: '/products/m16drip/retro-canvas-low-tops.jpg',
    colors: [colors.brown, colors.grey, colors.white, colors.pink, colors.red],
  },
  {
    sku: 'M16-BLACK-LOAFER',
    name: 'Black Casual Loafers',
    sub: 'Slip-on loafers',
    description: 'A polished black slip-on loafer with a low-profile sole.',
    category: 'Footwear',
    priceKes: 4000,
    image: '/products/m16drip/black-casual-loafers.jpg',
  },
  {
    sku: 'M16-CHUNKY-SANDAL',
    name: 'Chunky Buckle Sandals',
    sub: 'Buckle-detail sandals',
    description: 'Open-toe sandals with a chunky sole and buckle details.',
    category: 'Footwear',
    priceKes: 3500,
    image: '/products/m16drip/chunky-buckle-sandals.jpg',
    colors: [colors.black, { name: 'Olive', swatch: '#56614A' }],
  },
  {
    sku: 'M16-BLACK-SPORT-RUNNER',
    name: 'Black Sport Runners',
    sub: 'Chunky sports shoes',
    description: 'Black sports shoes with a sculpted, multi-part sole.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/black-sport-runners.jpg',
  },
  {
    sku: 'M16-BLACK-YELLOW-RUNNER',
    name: 'Black and Yellow Runners',
    sub: 'Colour-block sports shoes',
    description: 'Black runners with bold yellow accents.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/black-yellow-runners.jpg',
  },
  {
    sku: 'M16-BROWN-MULE',
    name: 'Brown Casual Mules',
    sub: 'Open-back slip-on shoes',
    description: 'Brown open-back slip-ons with a contrasting sole.',
    category: 'Footwear',
    priceKes: 3500,
    image: '/products/m16drip/brown-casual-mules.jpg',
  },
  {
    sku: 'M16-OLIVE-RUNNER',
    name: 'Olive Sport Runners',
    sub: 'Colour-block sports shoes',
    description: 'Olive runners with layered panels and a contrast sole.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/olive-sport-runners.jpg',
  },
  {
    sku: 'M16-WHITE-AIR-RUNNER',
    name: 'White Air-Style Runners',
    sub: 'Layered running shoes',
    description: 'White runners with layered panels and a cushioned-looking sole.',
    category: 'Footwear',
    priceKes: 5000,
    image: '/products/m16drip/white-air-style-runners.jpg',
  },
  {
    sku: 'M16-BLACK-RED-RUNNER',
    name: 'Black and Red Sport Runners',
    sub: 'Colour-block sports shoes',
    description: 'Black sports shoes with red contrast detailing.',
    category: 'Footwear',
    priceKes: 4500,
    image: '/products/m16drip/black-red-sport-runners.jpg',
  },
  {
    sku: 'M16-GRAPHIC-TEE',
    name: 'Graphic Cross T-Shirt',
    sub: 'Printed short-sleeve tee',
    description: 'A short-sleeve T-shirt with a bold cross graphic on the front.',
    category: 'Apparel',
    priceKes: 3000,
    image: '/products/m16drip/graphic-cross-t-shirt.jpg',
    colors: [colors.black, colors.red, colors.white],
  },
];

export const catalogBrand = {
  name: 'M16DRIPKICKS',
  blurb: 'Affordable apparel and footwear with nationwide delivery.',
  cta: 'Shop now',
};

export const catalogInitialStock = 10;

export const catalogCategories = ['Footwear', 'Apparel'] as const;
