CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  phone text,
  mpesa_phone text,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'customer' CHECK (role IN ('customer','admin')),
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE
);

CREATE TABLE brands (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  blurb text NOT NULL DEFAULT '',
  cta text NOT NULL DEFAULT 'Shop now'
);

CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  sub text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  category_id integer NOT NULL REFERENCES categories(id),
  brand_id integer REFERENCES brands(id),
  price_cents integer NOT NULL CHECK (price_cents >= 0),
  was_cents integer CHECK (was_cents IS NULL OR was_cents > 0),
  badge text,
  is_new integer NOT NULL DEFAULT 0,
  rating double precision NOT NULL DEFAULT 0,
  review_count integer NOT NULL DEFAULT 0,
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  sold integer NOT NULL DEFAULT 0,
  image text,
  sizes text NOT NULL DEFAULT '[]',
  colors text NOT NULL DEFAULT '[]',
  active integer NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX idx_products_category ON products(category_id);

CREATE TABLE orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  user_id integer NOT NULL REFERENCES users(id),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','shipped','delivered','cancelled')),
  payment_method text NOT NULL CHECK (payment_method IN ('card','mpesa','cod')),
  payment_status text NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','paid','cod','failed','refund_due')),
  payment_ref text,
  mpesa_receipt text,
  subtotal_cents integer NOT NULL,
  discount_cents integer NOT NULL DEFAULT 0,
  shipping_cents integer NOT NULL DEFAULT 0,
  total_cents integer NOT NULL,
  coupon_code text,
  shipping_method text NOT NULL,
  email text NOT NULL,
  ship_name text NOT NULL,
  ship_phone text NOT NULL,
  ship_line text NOT NULL,
  ship_city text NOT NULL,
  ship_country text NOT NULL DEFAULT 'Kenya',
  tracking text,
  note text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_created ON orders(created_at);

CREATE TABLE order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id),
  name text NOT NULL,
  sku text NOT NULL,
  price_cents integer NOT NULL,
  qty integer NOT NULL CHECK (qty > 0),
  size text,
  color text
);
CREATE INDEX idx_items_order ON order_items(order_id);

CREATE TABLE wishlist (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  PRIMARY KEY (user_id, product_id)
);

CREATE TABLE coupons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  tag text NOT NULL DEFAULT 'Offer',
  title text NOT NULL,
  note text NOT NULL DEFAULT '',
  type text NOT NULL CHECK (type IN ('percent','fixed','freeship')),
  value integer NOT NULL DEFAULT 0,
  min_spend_cents integer NOT NULL DEFAULT 0,
  expires_at text,
  one_per_user integer NOT NULL DEFAULT 0,
  auto_grant integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1
);

CREATE TABLE user_coupons (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  coupon_id integer NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, coupon_id)
);

CREATE TABLE addresses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label text NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  line1 text NOT NULL,
  line2 text,
  city text NOT NULL,
  country text NOT NULL DEFAULT 'Kenya',
  is_default integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_addresses_user ON addresses(user_id);
